# Categorías de Jokers
categoria.ANIMAL=Animal
categoria.AMIGABLE=Amigable
categoria.AGUA=Agua
categoria.COMIDA=Comida
categoria.DULCE=Dulce
categoria.BEBIDA=Bebida
categoria.AMARGO=Amargo
categoria.TRADICIONAL=Tradicional
categoria.INTERNACIONAL=Internacional
categoria.NACIONAL=Nacional
categoria.ALCOHOL=Alcohol
categoria.MUSICA=Musica
categoria.DEPORTE=Deporte
categoria.HISTORIA=Historia
categoria.OFICIO=Oficio
categoria.CAMPO=Campo
categoria.CIUDAD=Ciudad
categoria.NATURALEZA=Naturaleza
categoria.MASCOTA=Mascota
categoria.TRANSPORTE=Transporte
categoria.HERRAMIENTA=Herramienta
categoria.POSTRE=Postre
categoria.SECUENCIA=Secuencia
categoria.TV=TV
categoria.SALADO=Salado

# Rarezas
rareza.COMUN=Común
rareza.RARO=Raro
rareza.LEGENDARIO=Legendario
