# Categorías de Jokers
categoria.ANIMAL=Animal
categoria.AMIGABLE=Amigable
categoria.AGUA=Agua
categoria.COMIDA=Comida
categoria.DULCE=Dulce
categoria.BEBIDA=Bebida
categoria.AMARGO=Amargo
categoria.TRADICIONAL=Tradicional
categoria.INTERNACIONAL=Internacional
categoria.NACIONAL=Nacional
categoria.ALCOHOL=Alcohol

# Rarezas
rareza.COMUN=Común
rareza.RARO=Raro
rareza.LEGENDARIO=Legendario
