package io.github.HarryCodeProg.TrucoSurvivors.Estados;

public enum Accion {
    ENVIDO,
    REAL_ENVIDO,
    FALTA_ENVIDO,

    TRUCO,
    RETRUCO,
    VALE_CUATRO,

    IR_AL_MAZO,

    JUGAR_CARTA,
    DESCARTAR,

    QUIERO,
    NO_QUIERO,

    COMPRAR_ITEM_TIENDA,
    VENDER_JOKER,
    REROLL_CARTAS,
    REROLL_JOKERS,
    CONTINUAR_TIENDA,
    CONFIRMAR_SANTO,
    COMPRAR_Y_USAR_SANTO,
    CONFIRMAR_SELECCION_SANTO,
    USAR_SANTO,
    VENDER_SANTO
}
